=== b3dgs/lionengine/lionengine-game/src/main/xsd/com/b3dgs/lionengine/game/feature/tile/map/transition/tileTransitions.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema targetNamespace="http://lionengine.b3dgs.com/xsd/10" elementFormDefault="qualified" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:lionengine="http://lionengine.b3dgs.com/xsd/10">
    <xsd:complexType name="tile">
        <xsd:attribute name="number" type="xsd:int" use="required"></xsd:attribute>
    </xsd:complexType>
    <xsd:complexType name="transition">
        <xsd:sequence maxOccurs="1" minOccurs="1">
            <xsd:element name="tile" type="lionengine:tile" maxOccurs="unbounded" minOccurs="1"></xsd:element>
        </xsd:sequence>
        <xsd:attribute name="in" type="xsd:string" use="required"></xsd:attribute>
        <xsd:attribute name="out" type="xsd:string" use="required"></xsd:attribute>
        <xsd:attribute name="type" use="required">
            <xsd:simpleType>
                <xsd:restriction base="xsd:string">
                    <xsd:enumeration value="CENTER"></xsd:enumeration>
                    <xsd:enumeration value="UP_LEFT"></xsd:enumeration>
                    <xsd:enumeration value="UP_RIGHT"></xsd:enumeration>
                    <xsd:enumeration value="UP"></xsd:enumeration>
                    <xsd:enumeration value="DOWN"></xsd:enumeration>
                    <xsd:enumeration value="DOWN_LEFT"></xsd:enumeration>
                    <xsd:enumeration value="DOWN_RIGHT"></xsd:enumeration>
                    <xsd:enumeration value="LEFT"></xsd:enumeration>
                    <xsd:enumeration value="RIGHT"></xsd:enumeration>
                    <xsd:enumeration value="UP_LEFT_DOWN_RIGHT"></xsd:enumeration>
                    <xsd:enumeration value="UP_RIGHT_DOWN_LEFT"></xsd:enumeration>
                    <xsd:enumeration value="CORNER_UP_LEFT"></xsd:enumeration>
                    <xsd:enumeration value="CORNER_UP_RIGHT"></xsd:enumeration>
                    <xsd:enumeration value="CORNER_DOWN_LEFT"></xsd:enumeration>
                    <xsd:enumeration value="CORNER_DOWN_RIGHT"></xsd:enumeration>
                </xsd:restriction>
            </xsd:simpleType>
        </xsd:attribute>
    </xsd:complexType>
    <xsd:complexType name="transitions">
        <xsd:sequence maxOccurs="1" minOccurs="1">
            <xsd:element name="transition" type="lionengine:transition" maxOccurs="unbounded" minOccurs="0"></xsd:element>
        </xsd:sequence>
    </xsd:complexType>
    <xsd:element name="transitions" type="lionengine:transitions"></xsd:element>
</xsd:schema>

=== b3dgs/lionengine/lionengine-examples/src/main/resources/com/b3dgs/lionengine/example/game/fog/fog.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<lionengine:transitions xmlns:lionengine="http://lionengine.b3dgs.com/xsd/10" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://lionengine.b3dgs.com/xsd/10 http://lionengine.b3dgs.com/xsd/10/game/feature/tile/map/transition/tileTransitions.xsd">
    <lionengine:transition in="fog" out="none" type="UP">
        <lionengine:tile number="0"/>
    </lionengine:transition>
    <lionengine:transition in="fog" out="none" type="DOWN">
        <lionengine:tile number="1"/>
    </lionengine:transition>
    <lionengine:transition in="fog" out="none" type="RIGHT">
        <lionengine:tile number="2"/>
    </lionengine:transition>
    <lionengine:transition in="fog" out="none" type="LEFT">
        <lionengine:tile number="3"/>
    </lionengine:transition>
    <lionengine:transition in="fog" out="none" type="CORNER_UP_LEFT">
        <lionengine:tile number="7"/>
    </lionengine:transition>
    <lionengine:transition in="fog" out="none" type="CORNER_UP_RIGHT">
        <lionengine:tile number="6"/>
    </lionengine:transition>
    <lionengine:transition in="fog" out="none" type="CORNER_DOWN_LEFT">
        <lionengine:tile number="5"/>
    </lionengine:transition>
    <lionengine:transition in="fog" out="none" type="CORNER_DOWN_RIGHT">
        <lionengine:tile number="4"/>
    </lionengine:transition>
    <lionengine:transition in="fog" out="none" type="UP_LEFT">
        <lionengine:tile number="8"/>
    </lionengine:transition>
    <lionengine:transition in="fog" out="none" type="UP_RIGHT">
        <lionengine:tile number="9"/>
    </lionengine:transition>
    <lionengine:transition in="fog" out="none" type="DOWN_LEFT">
        <lionengine:tile number="10"/>
    </lionengine:transition>
    <lionengine:transition in="fog" out="none" type="DOWN_RIGHT">
        <lionengine:tile number="11"/>
    </lionengine:transition>
    <lionengine:transition in="fog" out="none" type="UP_LEFT_DOWN_RIGHT">
        <lionengine:tile number="13"/>
    </lionengine:transition>
    <lionengine:transition in="fog" out="none" type="UP_RIGHT_DOWN_LEFT">
        <lionengine:tile number="12"/>
    </lionengine:transition>
    <lionengine:transition in="none" out="fog" type="DOWN">
        <lionengine:tile number="0"/>
    </lionengine:transition>
    <lionengine:transition in="none" out="fog" type="UP">
        <lionengine:tile number="1"/>
    </lionengine:transition>
    <lionengine:transition in="none" out="fog" type="LEFT">
        <lionengine:tile number="2"/>
    </lionengine:transition>
    <lionengine:transition in="none" out="fog" type="RIGHT">
        <lionengine:tile number="3"/>
    </lionengine:transition>
    <lionengine:transition in="none" out="fog" type="UP_LEFT">
        <lionengine:tile number="7"/>
    </lionengine:transition>
    <lionengine:transition in="none" out="fog" type="UP_RIGHT">
        <lionengine:tile number="6"/>
    </lionengine:transition>
    <lionengine:transition in="none" out="fog" type="DOWN_LEFT">
        <lionengine:tile number="5"/>
    </lionengine:transition>
    <lionengine:transition in="none" out="fog" type="DOWN_RIGHT">
        <lionengine:tile number="4"/>
    </lionengine:transition>
    <lionengine:transition in="none" out="fog" type="CORNER_UP_LEFT">
        <lionengine:tile number="8"/>
    </lionengine:transition>
    <lionengine:transition in="none" out="fog" type="CORNER_UP_RIGHT">
        <lionengine:tile number="9"/>
    </lionengine:transition>
    <lionengine:transition in="none" out="fog" type="CORNER_DOWN_LEFT">
        <lionengine:tile number="10"/>
    </lionengine:transition>
    <lionengine:transition in="none" out="fog" type="CORNER_DOWN_RIGHT">
        <lionengine:tile number="11"/>
    </lionengine:transition>
    <lionengine:transition in="none" out="fog" type="UP_RIGHT_DOWN_LEFT">
        <lionengine:tile number="13"/>
    </lionengine:transition>
    <lionengine:transition in="none" out="fog" type="UP_LEFT_DOWN_RIGHT">
        <lionengine:tile number="12"/>
    </lionengine:transition>
    <lionengine:transition in="none" out="none" type="CENTER">
        <lionengine:tile number="17"/>
    </lionengine:transition>
    <lionengine:transition in="fog" out="fog" type="CENTER">
        <lionengine:tile number="16"/>
    </lionengine:transition>
</lionengine:transitions>
