=== b3dgs/lionengine/lionengine-helper/src/main/xsd/com/b3dgs/lionengine/helper/input.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema targetNamespace="http://lionengine.b3dgs.com/xsd/10" elementFormDefault="qualified" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:lionengine="http://lionengine.b3dgs.com/xsd/10">
    <xsd:complexType name="device">
        <xsd:sequence maxOccurs="1" minOccurs="0">
            <xsd:element name="horizontal" type="lionengine:horizontal" maxOccurs="unbounded" minOccurs="0"></xsd:element>
            <xsd:element name="vertical" type="lionengine:horizontal" maxOccurs="unbounded" minOccurs="0"></xsd:element>
            <xsd:element name="fire" type="lionengine:fire" maxOccurs="unbounded" minOccurs="0"></xsd:element>
        </xsd:sequence>
        <xsd:attribute name="class" type="xsd:string" use="required"></xsd:attribute>
        <xsd:attribute name="id" type="xsd:int" use="optional"></xsd:attribute>
        <xsd:attribute name="index" type="xsd:int" use="required"></xsd:attribute>
        <xsd:attribute name="name" type="xsd:string" use="required"></xsd:attribute>
        <xsd:attribute name="disabled" type="xsd:boolean" use="optional"></xsd:attribute>
    </xsd:complexType>
    <xsd:complexType name="horizontal">
        <xsd:attribute name="negative" type="xsd:int" use="required"></xsd:attribute>
        <xsd:attribute name="positive" type="xsd:int" use="required"></xsd:attribute>
    </xsd:complexType>
    <xsd:complexType name="vertical">
        <xsd:attribute name="negative" type="xsd:int" use="required"></xsd:attribute>
        <xsd:attribute name="positive" type="xsd:int" use="required"></xsd:attribute>
    </xsd:complexType>
    <xsd:complexType name="fire">
        <xsd:attribute name="index" type="xsd:string" use="required"></xsd:attribute>
        <xsd:attribute name="positive" type="xsd:int" use="required"></xsd:attribute>
    </xsd:complexType>
    <xsd:complexType name="input">
        <xsd:sequence maxOccurs="1" minOccurs="0">
            <xsd:element name="device" type="lionengine:device" maxOccurs="unbounded" minOccurs="1"></xsd:element>
        </xsd:sequence>
        <xsd:attribute name="mapping" type="xsd:string" use="required"></xsd:attribute>
    </xsd:complexType>
    <xsd:element name="input" type="lionengine:input"></xsd:element>
</xsd:schema>

=== b3dgs/lionengine/lionengine-examples/src/main/resources/com/b3dgs/lionengine/example/game/state/input.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<lionengine:input mapping="com.b3dgs.lionengine.example.game.state.DeviceMapping" xmlns:lionengine="http://lionengine.b3dgs.com/xsd/10" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://lionengine.b3dgs.com/xsd/10 http://lionengine.b3dgs.com/xsd/10/helper/input.xsd">
    <lionengine:device class="com.b3dgs.lionengine.awt.Keyboard" id="0" index="0" name="Arrow keys">
        <lionengine:horizontal negative="37" positive="39"/>
        <lionengine:vertical negative="40" positive="38"/>
        <lionengine:fire index="JUMP" positive="16"/>
        <lionengine:fire index="RUN" positive="16"/>
        <lionengine:fire index="ATTACK" positive="17"/>
        <lionengine:fire index="DEFEND" positive="18"/>
    </lionengine:device>
    <lionengine:device class="com.b3dgs.lionengine.awt.Keyboard" id="0" index="1" name="Left keyboard">
        <lionengine:horizontal negative="81" positive="68"/>
        <lionengine:vertical negative="83" positive="90"/>
        <lionengine:fire index="JUMP" positive="71"/>
        <lionengine:fire index="RUN" positive="16711696"/>
        <lionengine:fire index="ATTACK" positive="69"/>
        <lionengine:fire index="DEFEND" positive="65"/>
    </lionengine:device>
</lionengine:input>

=== b3dgs/lionengine/lionengine-tutorials/src/main/resources/com/b3dgs/lionengine/tutorials/mario/c/input.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<lionengine:input mapping="com.b3dgs.lionengine.tutorials.mario.c.DeviceMapping" xmlns:lionengine="http://lionengine.b3dgs.com/xsd/10" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://lionengine.b3dgs.com/xsd/10 http://lionengine.b3dgs.com/xsd/10/helper/input.xsd">
    <lionengine:device class="com.b3dgs.lionengine.awt.Keyboard" name="control" index="0">
        <lionengine:horizontal positive="39" negative="37"/>
        <lionengine:horizontal positive="68" negative="81"/>
        <lionengine:horizontal positive="102" negative="100"/>
        <lionengine:vertical positive="38" negative="40"/>
        <lionengine:vertical positive="90" negative="83"/>
        <lionengine:vertical positive="104" negative="98"/>
        <lionengine:fire index="LEFT" positive="68"/>
        <lionengine:fire index="LEFT" positive="37"/>
        <lionengine:fire index="LEFT" positive="102"/>
        <lionengine:fire index="RIGHT" positive="81"/>
        <lionengine:fire index="RIGHT" positive="100"/>
        <lionengine:fire index="RIGHT" positive="39"/>
        <lionengine:fire index="UP" positive="38"/>
        <lionengine:fire index="UP" positive="104"/>
        <lionengine:fire index="UP" positive="90"/>
        <lionengine:fire index="DOWN" positive="98"/>
        <lionengine:fire index="DOWN" positive="83"/>
        <lionengine:fire index="DOWN" positive="40"/>
        <lionengine:fire index="CTRL_RIGHT" positive="16"/>
        <lionengine:fire index="CTRL_RIGHT" positive="32"/>
        <lionengine:fire index="CTRL_RIGHT" positive="96"/>
        <lionengine:fire index="CTRL_RIGHT" positive="17"/>
        <lionengine:fire index="CTRL_RIGHT" positive="10"/>
    </lionengine:device>
</lionengine:input>
