=== b3dgs/lionengine/lionengine-game/src/main/xsd/com/b3dgs/lionengine/game/feature/tile/map/collision/tileFormulas.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema targetNamespace="http://lionengine.b3dgs.com/xsd/10" elementFormDefault="qualified" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:lionengine="http://lionengine.b3dgs.com/xsd/10">
    <xsd:complexType name="constraint">
        <xsd:attribute name="group" type="xsd:string" use="required"></xsd:attribute>
        <xsd:attribute name="orientation" use="required">
            <xsd:simpleType>
                <xsd:restriction base="xsd:string">
                    <xsd:enumeration value="NORTH"></xsd:enumeration>
                    <xsd:enumeration value="SOUTH"></xsd:enumeration>
                    <xsd:enumeration value="EAST"></xsd:enumeration>
                    <xsd:enumeration value="WEST"></xsd:enumeration>
                </xsd:restriction>
            </xsd:simpleType>
        </xsd:attribute>
    </xsd:complexType>
    <xsd:complexType name="function">
        <xsd:attribute name="type" use="required">
            <xsd:simpleType>
                <xsd:restriction base="xsd:string">
                    <xsd:enumeration value="LINEAR"></xsd:enumeration>
                </xsd:restriction>
            </xsd:simpleType>
        </xsd:attribute>
        <xsd:attribute name="a" type="xsd:double" use="required"></xsd:attribute>
        <xsd:attribute name="b" type="xsd:double" use="required"></xsd:attribute>
    </xsd:complexType>
    <xsd:complexType name="range">
        <xsd:attribute name="output" use="required">
            <xsd:simpleType>
                <xsd:restriction base="xsd:string">
                    <xsd:enumeration value="X"></xsd:enumeration>
                    <xsd:enumeration value="Y"></xsd:enumeration>
                </xsd:restriction>
            </xsd:simpleType>
        </xsd:attribute>
        <xsd:attribute name="minX" type="xsd:int" use="required"></xsd:attribute>
        <xsd:attribute name="maxX" type="xsd:int" use="required"></xsd:attribute>
        <xsd:attribute name="minY" type="xsd:int" use="required"></xsd:attribute>
        <xsd:attribute name="maxY" type="xsd:int" use="required"></xsd:attribute>
    </xsd:complexType>
    <xsd:complexType name="formula">
        <xsd:sequence maxOccurs="1" minOccurs="1">
            <xsd:element name="range" type="lionengine:range" maxOccurs="1" minOccurs="1"></xsd:element>
            <xsd:element name="function" type="lionengine:function" maxOccurs="1" minOccurs="1"></xsd:element>
            <xsd:element name="constraint" type="lionengine:constraint" maxOccurs="1" minOccurs="0"></xsd:element>
        </xsd:sequence>
        <xsd:attribute name="name" type="xsd:string" use="required"></xsd:attribute>
    </xsd:complexType>
    <xsd:complexType name="formulas">
        <xsd:sequence maxOccurs="1" minOccurs="1">
            <xsd:element name="formula" type="lionengine:formula" maxOccurs="unbounded" minOccurs="0"></xsd:element>
        </xsd:sequence>
    </xsd:complexType>
    <xsd:element name="formulas" type="lionengine:formulas"></xsd:element>
</xsd:schema>

=== b3dgs/lionengine/lionengine-game/src/it/resources/com/b3dgs/lionengine/game/it/feature/tile/map/collision/formulas.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<lionengine:formulas xmlns:lionengine="http://lionengine.b3dgs.com/xsd/10" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://lionengine.b3dgs.com/xsd/10 http://lionengine.b3dgs.com/xsd/10/game/feature/tile/map/collision/tileFormulas.xsd">
    <lionengine:formula name="top">
        <lionengine:range output="Y" minX="0" maxX="17" minY="0" maxY="0"/>
        <lionengine:function type="LINEAR" a="0" b="17"/>
        <lionengine:constraint group="block" orientation="NORTH"/>
    </lionengine:formula>
    <lionengine:formula name="bottom">
        <lionengine:range output="Y" minX="0" maxX="17" minY="0" maxY="0"/>
        <lionengine:function type="LINEAR" a="0" b="0"/>
        <lionengine:constraint group="block" orientation="SOUTH"/>
    </lionengine:formula>
    <lionengine:formula name="left">
        <lionengine:range output="X" minX="0" maxX="1" minY="0" maxY="17"/>
        <lionengine:function type="LINEAR" a="0" b="0"/>
        <lionengine:constraint group="block" orientation="WEST"/>
    </lionengine:formula>
    <lionengine:formula name="right">
        <lionengine:range output="X" minX="0" maxX="1" minY="0" maxY="17"/>
        <lionengine:function type="LINEAR" a="0" b="17"/>
        <lionengine:constraint group="block" orientation="EAST"/>
    </lionengine:formula>
</lionengine:formulas>

=== b3dgs/lionengine/lionengine-examples/src/main/resources/com/b3dgs/lionengine/example/game/collision/formulas.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<lionengine:formulas xmlns:lionengine="http://lionengine.b3dgs.com/xsd/10" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://lionengine.b3dgs.com/xsd/10 http://lionengine.b3dgs.com/xsd/10/game/feature/tile/map/collision/tileFormulas.xsd">
    <lionengine:formula name="ground">
        <lionengine:range maxX="16" maxY="0" minX="0" minY="0" output="Y"/>
        <lionengine:function a="0.0" b="0.0" type="LINEAR"/>
    </lionengine:formula>
    <lionengine:formula name="slope_left_0">
        <lionengine:range maxX="16" maxY="0" minX="0" minY="0" output="Y"/>
        <lionengine:function a="0.5" b="0.0" type="LINEAR"/>
    </lionengine:formula>
    <lionengine:formula name="slope_left_1">
        <lionengine:range maxX="16" maxY="0" minX="0" minY="0" output="Y"/>
        <lionengine:function a="0.5" b="8.0" type="LINEAR"/>
    </lionengine:formula>
    <lionengine:formula name="slope_right_0">
        <lionengine:range maxX="16" maxY="0" minX="0" minY="0" output="Y"/>
        <lionengine:function a="-0.5" b="8.0" type="LINEAR"/>
    </lionengine:formula>
    <lionengine:formula name="slope_right_1">
        <lionengine:range maxX="16" maxY="0" minX="0" minY="0" output="Y"/>
        <lionengine:function a="-0.5" b="16.0" type="LINEAR"/>
    </lionengine:formula>
    <lionengine:formula name="steep_left">
        <lionengine:range maxX="16" maxY="0" minX="0" minY="0" output="Y"/>
        <lionengine:function a="1.0" b="0.0" type="LINEAR"/>
    </lionengine:formula>
    <lionengine:formula name="steep_right">
        <lionengine:range maxX="16" maxY="0" minX="0" minY="0" output="Y"/>
        <lionengine:function a="-1.0" b="16.0" type="LINEAR"/>
    </lionengine:formula>
</lionengine:formulas>
