=== b3dgs/lionengine/lionengine-game/src/main/xsd/com/b3dgs/lionengine/game/feature/tile/map/transition/circuit/tileCircuits.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema targetNamespace="http://lionengine.b3dgs.com/xsd/10" elementFormDefault="qualified" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:lionengine="http://lionengine.b3dgs.com/xsd/10">
    <xsd:complexType name="tile">
        <xsd:attribute name="number" type="xsd:int" use="required"></xsd:attribute>
    </xsd:complexType>
    <xsd:complexType name="circuit">
        <xsd:sequence maxOccurs="1" minOccurs="1">
            <xsd:element name="tile" type="lionengine:tile" maxOccurs="unbounded" minOccurs="1"></xsd:element>
        </xsd:sequence>
        <xsd:attribute name="in" type="xsd:string" use="required"></xsd:attribute>
        <xsd:attribute name="out" type="xsd:string" use="required"></xsd:attribute>
        <xsd:attribute name="type" use="required">
            <xsd:simpleType>
                <xsd:restriction base="xsd:string">
                    <xsd:enumeration value="TOP"></xsd:enumeration>
                    <xsd:enumeration value="BOTTOM"></xsd:enumeration>
                    <xsd:enumeration value="LEFT"></xsd:enumeration>
                    <xsd:enumeration value="RIGHT"></xsd:enumeration>
                    <xsd:enumeration value="HORIZONTAL"></xsd:enumeration>
                    <xsd:enumeration value="VERTICAL"></xsd:enumeration>
                    <xsd:enumeration value="ANGLE_TOP_LEFT"></xsd:enumeration>
                    <xsd:enumeration value="ANGLE_TOP_RIGHT"></xsd:enumeration>
                    <xsd:enumeration value="ANGLE_BOTTOM_LEFT"></xsd:enumeration>
                    <xsd:enumeration value="ANGLE_BOTTOM_RIGHT"></xsd:enumeration>
                    <xsd:enumeration value="T3J_TOP"></xsd:enumeration>
                    <xsd:enumeration value="T3J_BOTTOM"></xsd:enumeration>
                    <xsd:enumeration value="T3J_LEFT"></xsd:enumeration>
                    <xsd:enumeration value="T3J_RIGHT"></xsd:enumeration>
                    <xsd:enumeration value="MIDDLE"></xsd:enumeration>
                    <xsd:enumeration value="BLOCK"></xsd:enumeration>
                </xsd:restriction>
            </xsd:simpleType>
        </xsd:attribute>
    </xsd:complexType>
    <xsd:complexType name="circuits">
        <xsd:sequence maxOccurs="1" minOccurs="1">
            <xsd:element name="circuit" type="lionengine:circuit" maxOccurs="unbounded" minOccurs="0"></xsd:element>
        </xsd:sequence>
    </xsd:complexType>
    <xsd:element name="circuits" type="lionengine:circuits"></xsd:element>
</xsd:schema>

=== b3dgs/lionengine/lionengine-game/src/test/resources/com/b3dgs/lionengine/game/feature/tile/map/transition/circuit/generator/circuits.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<lionengine:circuits xmlns:lionengine="http://lionengine.b3dgs.com/xsd/10" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://lionengine.b3dgs.com/xsd/10 http://lionengine.b3dgs.com/xsd/10/game/feature/tile/map/transition/circuit/tileCircuits.xsd">
    <lionengine:circuit in="road" out="grass" type="T3J_RIGHT">
        <lionengine:tile number="17"/>
    </lionengine:circuit>
    <lionengine:circuit in="road" out="road" type="MIDDLE">
        <lionengine:tile number="16"/>
    </lionengine:circuit>
    <lionengine:circuit in="road" out="grass" type="ANGLE_TOP_RIGHT">
        <lionengine:tile number="5"/>
    </lionengine:circuit>
    <lionengine:circuit in="road" out="grass" type="T3J_BOTTOM">
        <lionengine:tile number="22"/>
    </lionengine:circuit>
    <lionengine:circuit in="road" out="grass" type="VERTICAL">
        <lionengine:tile number="9"/>
    </lionengine:circuit>
    <lionengine:circuit in="road" out="grass" type="T3J_LEFT">
        <lionengine:tile number="14"/>
    </lionengine:circuit>
    <lionengine:circuit in="road" out="grass" type="ANGLE_TOP_LEFT">
        <lionengine:tile number="1"/>
    </lionengine:circuit>
    <lionengine:circuit in="road" out="grass" type="ANGLE_BOTTOM_RIGHT">
        <lionengine:tile number="23"/>
    </lionengine:circuit>
    <lionengine:circuit in="road" out="grass" type="TOP">
        <lionengine:tile number="3"/>
    </lionengine:circuit>
    <lionengine:circuit in="road" out="grass" type="LEFT">
        <lionengine:tile number="4"/>
    </lionengine:circuit>
    <lionengine:circuit in="road" out="grass" type="T3J_TOP">
        <lionengine:tile number="10"/>
    </lionengine:circuit>
    <lionengine:circuit in="road" out="grass" type="HORIZONTAL">
        <lionengine:tile number="15"/>
    </lionengine:circuit>
    <lionengine:circuit in="road" out="grass" type="ANGLE_BOTTOM_LEFT">
        <lionengine:tile number="21"/>
    </lionengine:circuit>
    <lionengine:circuit in="road" out="grass" type="RIGHT">
        <lionengine:tile number="2"/>
    </lionengine:circuit>
    <lionengine:circuit in="road" out="grass" type="BOTTOM">
        <lionengine:tile number="24"/>
    </lionengine:circuit>
</lionengine:circuits>
