=== b3dgs/lionengine/lionengine-game/src/main/xsd/com/b3dgs/lionengine/game/feature/tile/map/pathfinding/pathfinding.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema targetNamespace="http://lionengine.b3dgs.com/xsd/10" elementFormDefault="qualified" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:lionengine="http://lionengine.b3dgs.com/xsd/10">
    <xsd:complexType name="tilePath">
        <xsd:sequence>
            <xsd:element name="group" type="xsd:string" maxOccurs="unbounded" minOccurs="1"></xsd:element>
        </xsd:sequence>
        <xsd:attribute name="category" type="xsd:string" use="required"></xsd:attribute>
    </xsd:complexType>
    <xsd:complexType name="pathfinding">
        <xsd:sequence maxOccurs="1" minOccurs="1">
            <xsd:element name="tilePath" type="lionengine:tilePath" maxOccurs="unbounded" minOccurs="0"></xsd:element>
        </xsd:sequence>
    </xsd:complexType>
    <xsd:element name="pathfinding" type="lionengine:pathfinding"></xsd:element>
</xsd:schema>

=== b3dgs/lionengine/lionengine-examples/src/main/resources/com/b3dgs/lionengine/example/game/pathfinding/pathfinding.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<lionengine:pathfinding xmlns:lionengine="http://lionengine.b3dgs.com/xsd/9" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://lionengine.b3dgs.com/xsd/9 http://lionengine.b3dgs.com/xsd/9/pathfinding.xsd">
    <lionengine:tilePath category="ground">
        <lionengine:group>grass</lionengine:group>
        <lionengine:group>road</lionengine:group>
    </lionengine:tilePath>
    <lionengine:tilePath category="waterBorder">
        <lionengine:group>waterBorder</lionengine:group>
    </lionengine:tilePath>
    <lionengine:tilePath category="tree">
        <lionengine:group>tree</lionengine:group>
        <lionengine:group>treeBorder</lionengine:group>
    </lionengine:tilePath>
    <lionengine:tilePath category="water">
        <lionengine:group>water</lionengine:group>
    </lionengine:tilePath>
</lionengine:pathfinding>

=== b3dgs/lionengine/lionengine-game/src/it/resources/com/b3dgs/lionengine/game/it/feature/selector/pathfinding.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<lionengine:pathfinding xmlns:lionengine="http://lionengine.b3dgs.com/xsd/10" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://lionengine.b3dgs.com/xsd/10 http://lionengine.b3dgs.com/xsd/10/game/feature/tile/map/pathfinding/pathfinding.xsd">
    <lionengine:tilePath category="ground">
        <lionengine:group>grassDark</lionengine:group>
        <lionengine:group>grassDarkBorder</lionengine:group>
        <lionengine:group>grass</lionengine:group>
        <lionengine:group>grassLightBorder</lionengine:group>
        <lionengine:group>grassLight</lionengine:group>
        <lionengine:group>grassBrightBorder</lionengine:group>
        <lionengine:group>grassBright</lionengine:group>
        <lionengine:group>road</lionengine:group>
        <lionengine:group>bridge</lionengine:group>
        <lionengine:group>treeCut</lionengine:group>
    </lionengine:tilePath>
    <lionengine:tilePath category="border">
        <lionengine:group>border</lionengine:group>
    </lionengine:tilePath>
    <lionengine:tilePath category="tree">
        <lionengine:group>tree</lionengine:group>
        <lionengine:group>treeBorder</lionengine:group>
    </lionengine:tilePath>
    <lionengine:tilePath category="water">
        <lionengine:group>water</lionengine:group>
    </lionengine:tilePath>
</lionengine:pathfinding>
